// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIM9xAK-GB1opSZ-ih7hFkhnd3h7krVQ',
    appId: '1:922224888586:web:fa4602819d30b29de108f3',
    messagingSenderId: '922224888586',
    projectId: 'agenmax-52847',
    authDomain: 'agenmax-52847.firebaseapp.com',
    storageBucket: 'agenmax-52847.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEBS2OmGv_TuvnviqzKjblpSbw-3hzxx4',
    appId: '1:922224888586:android:1890296767ca7375e108f3',
    messagingSenderId: '922224888586',
    projectId: 'agenmax-52847',
    storageBucket: 'agenmax-52847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2TcRH9jubNhvx6MCqvEljy_pI2pGAFE',
    appId: '1:922224888586:ios:f2cb8279e01acccbe108f3',
    messagingSenderId: '922224888586',
    projectId: 'agenmax-52847',
    storageBucket: 'agenmax-52847.appspot.com',
    iosClientId: '922224888586-9flgai9k9kp63fk4h31gfvhqs6sd8ski.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenmax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl2TcRH9jubNhvx6MCqvEljy_pI2pGAFE',
    appId: '1:922224888586:ios:f2cb8279e01acccbe108f3',
    messagingSenderId: '922224888586',
    projectId: 'agenmax-52847',
    storageBucket: 'agenmax-52847.appspot.com',
    iosClientId: '922224888586-9flgai9k9kp63fk4h31gfvhqs6sd8ski.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenmax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIM9xAK-GB1opSZ-ih7hFkhnd3h7krVQ',
    appId: '1:922224888586:web:16d5e987b139efafe108f3',
    messagingSenderId: '922224888586',
    projectId: 'agenmax-52847',
    authDomain: 'agenmax-52847.firebaseapp.com',
    storageBucket: 'agenmax-52847.appspot.com',
  );
}
